export const CONSTANTS = {
    TITLE: "\"If at first you do not succeed, call it version 1.0\"",
    DESCRIPTION: "I've been working, programming in some capacity for nearly a decade now, but I've always had a passion for it, even if just as a hobby in the beginning. After getting a job as a developer, a few years later, I realized I didn't really have any projects to show in a portfolio other than official work projects, so I made it a habit to start periodically working on projects. [This site is one of them!]. Hope you have fun exploring and if you have any questions about any of the projects here, feel free to reach out!",
    MERN_DESC: "I decided to do my own MERN stack project because I had never done one solo, and it seemed like a good learning experience. While I was creating it, I thought it would be cool to have it work in real-time, so I added websocket to it, to create always open connections. Unfortunately I would have to pay for hosting, and because this was just a simple hobby project, I didn't host it, but I put all of the code in github, where you can look at it, and run on your own machine. Even though everything is in one respository, it requires starting the front-end and backend separately.",
    SV_DESC: "Another holiday React-based project. I decided to create a website that allowed users to record their game records and take notes on games. You could then view your own stats, or the stats of everyone on the site. It was subdivided by different decks, and you could also see notes of other players based on class and deck. I mainly focused on user profile and authentication using firebase. Its not maintained anymore but the records are still there.",
    LIFE_DESC: "Oh man, I remember this one. When I was first learning React, this was one of the first projects I created that I was really proud of! I must have gone through the same react tutorial like 5 times. Even today, looking at this one makes me smile.",
    MARK_DESC: "Another React project that allows you to type and then see the output as Markdown. Simple project, but it was good for learning basic React textbox rendering fundamentals!",
    SIMON_DESC: "Built in jQuery, the first game I ever made using code. its a simon-says clone with a twist. Each level is a new monster you have to defeat and as you progress, you get items you can use to help win the game. I built a lot of this while I was visiting home and hanging out in the College of Charleston Computer Science Student Lounge, where my friend was going to school at the time. Thanks to all of those kind folks who gave me advice on this one. For experts, it even has a hard mode!",
    WIKI_DESC: "Back when I was learning programming this was a project I did using jquery to build a simple search site that utilizes the free Wikipedia API. It also has functionality to show you random Wikipedia Pages.",
    CALC_DESC: "Simple calculator made in jQuery. This was one of my first projects ever and hoo-boy I'm sure you could find a bug or two in here. Part of me wants to update it, but at the same time, I feel like its a great piece on seeing how far I've come. Like looking at your baby photos. Ya know what I mean?",
    LESS_INFO: "Less Info",
    MORE_INFO: "More Info"
}